# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import apotekz_pb2 as apotekz__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in apotekz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MedicineServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMedicine = channel.unary_unary(
                '/MedicineService/AddMedicine',
                request_serializer=apotekz__pb2.Medicine.SerializeToString,
                response_deserializer=apotekz__pb2.Medicine.FromString,
                _registered_method=True)
        self.GetAllMedicines = channel.unary_unary(
                '/MedicineService/GetAllMedicines',
                request_serializer=apotekz__pb2.Empty.SerializeToString,
                response_deserializer=apotekz__pb2.MedicineList.FromString,
                _registered_method=True)
        self.GetMedicine = channel.unary_unary(
                '/MedicineService/GetMedicine',
                request_serializer=apotekz__pb2.MedicineId.SerializeToString,
                response_deserializer=apotekz__pb2.Medicine.FromString,
                _registered_method=True)
        self.UpdateMedicine = channel.unary_unary(
                '/MedicineService/UpdateMedicine',
                request_serializer=apotekz__pb2.Medicine.SerializeToString,
                response_deserializer=apotekz__pb2.Medicine.FromString,
                _registered_method=True)
        self.DeleteMedicine = channel.unary_unary(
                '/MedicineService/DeleteMedicine',
                request_serializer=apotekz__pb2.MedicineId.SerializeToString,
                response_deserializer=apotekz__pb2.Empty.FromString,
                _registered_method=True)


class MedicineServiceServicer(object):
    """Service
    """

    def AddMedicine(self, request, context):
        """Create
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMedicines(self, request, context):
        """Read 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMedicine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMedicine(self, request, context):
        """Update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMedicine(self, request, context):
        """Delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMedicine,
                    request_deserializer=apotekz__pb2.Medicine.FromString,
                    response_serializer=apotekz__pb2.Medicine.SerializeToString,
            ),
            'GetAllMedicines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMedicines,
                    request_deserializer=apotekz__pb2.Empty.FromString,
                    response_serializer=apotekz__pb2.MedicineList.SerializeToString,
            ),
            'GetMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMedicine,
                    request_deserializer=apotekz__pb2.MedicineId.FromString,
                    response_serializer=apotekz__pb2.Medicine.SerializeToString,
            ),
            'UpdateMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMedicine,
                    request_deserializer=apotekz__pb2.Medicine.FromString,
                    response_serializer=apotekz__pb2.Medicine.SerializeToString,
            ),
            'DeleteMedicine': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMedicine,
                    request_deserializer=apotekz__pb2.MedicineId.FromString,
                    response_serializer=apotekz__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MedicineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MedicineService(object):
    """Service
    """

    @staticmethod
    def AddMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MedicineService/AddMedicine',
            apotekz__pb2.Medicine.SerializeToString,
            apotekz__pb2.Medicine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMedicines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MedicineService/GetAllMedicines',
            apotekz__pb2.Empty.SerializeToString,
            apotekz__pb2.MedicineList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MedicineService/GetMedicine',
            apotekz__pb2.MedicineId.SerializeToString,
            apotekz__pb2.Medicine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MedicineService/UpdateMedicine',
            apotekz__pb2.Medicine.SerializeToString,
            apotekz__pb2.Medicine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMedicine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MedicineService/DeleteMedicine',
            apotekz__pb2.MedicineId.SerializeToString,
            apotekz__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
