# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apotekz.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapotekz.proto\"[\n\x08Medicine\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x15\n\rdelivery_type\x18\x05 \x01(\t\",\n\x0cMedicineList\x12\x1c\n\tmedicines\x18\x01 \x03(\x0b\x32\t.Medicine\"\x18\n\nMedicineId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xe0\x01\n\x0fMedicineService\x12%\n\x0b\x41\x64\x64Medicine\x12\t.Medicine\x1a\t.Medicine\"\x00\x12*\n\x0fGetAllMedicines\x12\x06.Empty\x1a\r.MedicineList\"\x00\x12\'\n\x0bGetMedicine\x12\x0b.MedicineId\x1a\t.Medicine\"\x00\x12(\n\x0eUpdateMedicine\x12\t.Medicine\x1a\t.Medicine\"\x00\x12\'\n\x0e\x44\x65leteMedicine\x12\x0b.MedicineId\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apotekz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDICINE']._serialized_start=17
  _globals['_MEDICINE']._serialized_end=108
  _globals['_MEDICINELIST']._serialized_start=110
  _globals['_MEDICINELIST']._serialized_end=154
  _globals['_MEDICINEID']._serialized_start=156
  _globals['_MEDICINEID']._serialized_end=180
  _globals['_EMPTY']._serialized_start=182
  _globals['_EMPTY']._serialized_end=189
  _globals['_MEDICINESERVICE']._serialized_start=192
  _globals['_MEDICINESERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
